# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d78dc53a904f598a3601aeb97a2b56d90462c739c6ea63f9c99ea32d94f8babfe39fdaaa8a06296753d2c38c2876eb107e73a963928c510221e45c93e9e36ec

test:
  secret_key_base: 01dac532dae2648309e122ef82cc10d51547e6e09297e41ec6371ec4be7471a688b01285332cf4961a2424df261c440c06bf105e1fe7c825f1a884b7e03d9310

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
